services:
  - type: web
    name: facebook-bot-webhook
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    port: 8000
    envVars:
      - key: FACEBOOK_PAGE_ACCESS_TOKEN
        fromSecret: FACEBOOK_PAGE_ACCESS_TOKEN
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: GETIMG_API_KEY
        fromSecret: GETIMG_API_KEY
      - key: ASSEMBLYAI_API_KEY
        fromSecret: ASSEMBLYAI_API_KEY
      - key: VERIFY_TOKEN
        fromSecret: VERIFY_TOKEN